config/routes.rb
Rails.application.routes.draw do
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#show', via: :get, :as => :admin_checkout
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#update', via: :put

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  resources :orders

  get 'ping' => proc {|env| [200, {}, []] }

  resources :offers, only: :index do
    resources :checkout, controller: 'offers/checkout'do
      post "/" => "offers/checkout#show"
    end
  	collection do
  		get "show" => "offers#show"
      get "broadband_providers" => "offers#broadband_providers", :constraints => {:format => /(json)/}
  	end
  end

  %w(cox charter_spectrum twc dashboard).each do |proivder|
    get proivder => "landings##{proivder}"
  end

  get "/compare_packages" => "landings#compare_packages"
  get "/load_channels" => "landings#load_channels"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  devise_for :users, :skip => [:registrations], controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'registration'
    delete 'users/:id' => 'devise/registrations#destroy', :as => 'destroy_user_registration'
  end

  resources :call_back, only: [:create]
  root to: 'landings#index'
end

app/views/shared/_call_back_form.html.erb
<div class="modal fade" id="call_back" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= simple_form_for CallBack.new, url: call_back_index_path, method: :post, html: { onsubmit: "requestCallback(event);" } do |f |%>
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">
            <div class="panel panel-un">
              <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span>Feel free to Request a Call Back from us!</span>
              </div>
            </div>
          </h4>
        </div>
        <div class="modal-body">
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.input :first_name, placeholder: "First Name" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.input :last_name, placeholder: "Last Name" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.input :email, placeholder: "Email" %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.label :phone_no %>
                <div class="input-group">
                  <div class="input-group-addon"><i class="fa fa-mobile"></i></div>
                  <%= f.input :phone_no, label: false, placeholder: "Phone" %>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-6">
              <div class="form-group">
                <%= f.input :address, as: :text, placeholder: "Street Address", input_html: { rows: 5 } %>
              </div>
            </div>
            <div class="col-md-6">
              <div class="form-group">
                <%= f.input :state, placeholder: "State" %>
              </div>
              <div class="form-group">
                <%= f.input :zip, placeholder: "Zip Code" %>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-4">
              <div class="form-group">
                <%= f.label :preferred_time, "*Preferred Time" %>
                <div class="input-group time_fields">
                  <span class="input-group-addon"><span class="fa fa-clock-o"></span></span>
                  <%= f.input :preferred_time, label: false, as: :string, placeholder: "Choose your preferred timings" %>
                </div>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= f.input :time_zone, collection: CallBack::TIMEZONE.map{|m| m}, include_blank: "--Select--" %>
              </div>
            </div>
            <div class="col-md-4">
              <div class="form-group">
                <%= f.label :preferred_date, "*Preferred Date" %>
                <div class="input-group date_fields">
                  <span class="input-group-addon"><span class="glyphicon glyphicon-calendar"></span></span>
                  <%= f.input :preferred_date, label: false, as: :string, placeholder: "Choose your preferred date" %>
                </div>
                
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <%= button_tag "Submit", type: :submit, class: "btn btn-un" %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_channel_list.html.erb
<div class="modal fade" id="channel-list" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Channel List</h4>
      </div>
      <div class="modal-body">
        <% if channels.present? %>
          <table class="table table-striped">
            <thead>
              <tr>
                <th>Channels</th>
                <% channel_names.each do |name| %>
                  <th style="font-size: 12px;"><%= name %></th>
                <% end %>
              </tr>
            </thead>
            <tbody>
              <% channels.each do |channel| %>
                <tr>
                  <td><%= channel["channel"] %></td>
                  <% channel_names.each do |name| %>
                    <% if channel[name.downcase.tr(" ", "_")] == name %>
                      <td><i class="fa fa-check-circle-o"></i></td>
                    <% else %>
                      <td>---</td>
                    <% end %>
                  <% end %>
                </tr>
              <% end %>
            </tbody>
          </table>
        <% else %>
          <div class="alert alert-danger">
            There are channels for <strong><%= provider_name %></strong>
          </div>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-un" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_compare_packages.html.erb
<div class="modal fade" id="compareModal" tabindex="-1" role="dialog" aria-labelledby="compareModal">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="compareModal">Comparing <%= pluralize(packages.count, "package") %></h4>
      </div>
      <div class="modal-body">
      	<div class="row">
      		<% packages.each do |package| %>
	      		<div class="<%= packages.length == 2 ? 'col-md-6 col-sm-6 col-xs-6' : 'col-md-4 col-sm-4 col-xs-4' %>">
	      			<div class="panel panel-default">
	      				<div class="panel-body">
	      					<blockquote>
										<%= provider_logo(package.provider) %>
									</blockquote>
									
									<div class="bs-callout bs-callout-danger" id="callout-collapse-dependency">
										<p style="font-weight: bold;"><%= package.package_name %></p>
									</div>
									<dl>
									  <dt>Package Type</dt>
									  <dd><%= package.package_type.name %></dd>
									</dl>
									<dl>
									  <dt>Price Info</dt>
									  <dd><%= package.price_info %></dd>
									</dl>
									<dl>
									  <dt>Price</dt>
									  <dd><%= package.price %></dd>
									</dl>
									<dl>
									  <dt>Promotion Disclaimer</dt>
									  <dd><%= package.promotion_disclaimer.nil? ? "N/A" : package.promotion_disclaimer %></dd>
									</dl>
									<dl>
									  <dt>Monthly Fee after Promotion</dt>
									  <dd><%= package.monthly_fee_after_promotion.nil? ? "N/A" : package.monthly_fee_after_promotion %></dd>
									</dl>
									<dl>
									  <dt>Installation Price</dt>
									  <dd><%= package.installation_price.nil? ? "N/A" : package.installation_price %></dd>
									</dl>
	      				</div>
		        	</div>
	      		</div>
    		 	<% end %>
      	</div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-un" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_filters.html.erb
<div class="tab-content packages-tab-content">
 <div role="tabpanel" class="tab-pane fade in active" id="filter_with_tv">
   <div class="row">
     <div id="cable_packages">
       <% if @tv_packages.present? %>
         <%= render partial: "shared/filtered_packages/cable", collection: @tv_packages, as: :tv_package %>
       <% else %>
         <div class="alert alert-warning">
           Sorry! No <strong>Cable</strong> Packages available
         </div>
       <% end %>
     </div>
   </div>

   <div class="row">
     <div class="col-md-4">
       <a href="#" class="channel-comparison-link" data-provider="<%= params[:action] %>">Channel List</a>
     </div>
     <div class="col-md-4 text-center">
       <%= will_paginate @tv_packages, renderer: BootstrapPagination::Rails %>
     </div>
     <div class="col-md-4">
       <% if @tv_packages.length > Package::PACKAGE_PER_PAGE_LENGTH %>
         <button class="btn btn-default pull-right see-more-btn" id="see-more-cable-packages" data-product="cable" onclick="loadPackages(this);">SEE MORE PACKAGES</button>
       <% end %>
     </div>
   </div>

 </div>
 <div role="tabpanel" class="tab-pane fade in" id="filter_with_internet">
   <div class="row">
     <div id="internet_packages">
       <% if @internet_packages.present? %>
         <%= render partial: "shared/filtered_packages/internet", collection: @internet_packages, as: :internet_package %>
       <% else %>
         <div class="alert alert-warning">
           Sorry! No <strong>Internet</strong> Packages available
         </div>
       <% end %>
     </div>
   </div>

   <div class="row">
     <div class="col-md-4">
       <!-- <a href="#" class="channel-comparison-link" data-provider="<%= params[:action] %>">CHANNEL COMPARISON</a> -->
     </div>
     <div class="col-md-4 text-center">
       <%= will_paginate @internet_packages, renderer: BootstrapPagination::Rails %>
     </div>
     <div class="col-md-4">
       <% if @internet_packages.length > Package::PACKAGE_PER_PAGE_LENGTH %>
         <button class="btn btn-default pull-right see-more-btn" id="see-more-internet-packages" data-product="internet" onclick="loadPackages(this);">SEE MORE PACKAGES</button>
       <% end %>
     </div>
   </div>

 </div>
 <div role="tabpanel" class="tab-pane fade in" id="filter_with_phone">
   <div class="row">
     <div id="phone_packages">
       <% if @phone_packages.present? %>
         <%= render partial: "shared/filtered_packages/phone", collection: @phone_packages, as: :phone_package %>
       <% else %>
         <div class="alert alert-warning">
           Sorry! No <strong>Phone</strong> Packages available
         </div>
       <% end %>
     </div>
   </div>

   <div class="row">
     <div class="col-md-4">
       <!-- <a href="#" class="channel-comparison-link" data-provider="<%= params[:action] %>">CHANNEL COMPARISON</a> -->
     </div>
     <div class="col-md-4 text-center">
       <%= will_paginate @phone_packages, renderer: BootstrapPagination::Rails %>
     </div>
     <div class="col-md-4">
       <% if @phone_packages.length > Package::PACKAGE_PER_PAGE_LENGTH %>
         <button class="btn btn-default pull-right see-more-btn" id="see-more-phone-packages" data-product="phone" onclick="loadPackages(this);">SEE MORE PACKAGES</button>
       <% end %>
     </div>
   </div>

 </div>
 <div role="tabpanel" class="tab-pane fade in" id="filter_with_bundles">
   <div class="row">
     <div id="bundle_packages">
       <% if @bundle_packages.present? %>
         <%= render partial: "shared/filtered_packages/bundles", collection: @bundle_packages, as: :bundle_package %>
       <% else %>
         <div class="alert alert-warning">
           Sorry! No Packages available
         </div>
       <% end %>
     </div>
   </div>

   <div class="row">
     <div class="col-md-4">
       <!-- <a href="#" class="channel-comparison-link" data-provider="<%= params[:action] %>">CHANNEL COMPARISON</a> -->
     </div>
     <div class="col-md-4 text-center">
       <%= will_paginate @bundle_packages, renderer: BootstrapPagination::Rails %>
     </div>
     <div class="col-md-4">
       <% if @bundle_packages.length > Package::PACKAGE_PER_PAGE_LENGTH %>
         <button class="btn btn-default pull-right see-more-btn" id="see-more-bundle-packages" data-product="bundle" onclick="loadPackages(this);">SEE MORE PACKAGES</button>
       <% end %>
     </div>
   </div>

 </div>
</div>

app/views/shared/_login.html.erb
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-sm" role="document">
    <div class="modal-content">
      <%= simple_form_for(User.new, as: resource_name, url: session_path(resource_name)) do |f| %>
        <div class="modal-header">
          <h4 class="modal-title" id="myModalLabel">
            <div class="panel panel-un">
              <div class="panel-heading">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <span>Login to your account!</span>
              </div>
            </div>
          </h4>
        </div>
        <div class="modal-body">
          <fieldset>
            <div class="row">
              <div class="center-block">
                <%= image_tag("user-login.png", class: "profile-img") %>
              </div>
            </div>
            <br />
            <div class="conatiner">
              <div class="row">
                <div class="col-md-12">
                  <div class="form-group">
                    <div class="input-group">
                      <span class="input-group-addon">
                        <i class="glyphicon glyphicon-user"></i>
                      </span>
                      <%= f.input :email, label: false, required: false, autofocus: true, placeholder: "Email" %>
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="input-group">
                      <span class="input-group-addon">
                        <i class="glyphicon glyphicon-lock"></i>
                      </span>
                      <%= f.input :password, required: false, label: false, placeholder: "Password" %>
                    </div>
                  </div>
                  <div class="form-group">
                     <div class="checkbox">
                       <%= f.check_box :remember_me, {:class => "styled"} if devise_mapping.rememberable? %>
                        <label>
                          Remember Me
                        </label>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            
          </fieldset>
        </div>
        <div class="modal-footer">
          <!-- <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button> -->
          <%= f.button :button, 'Sign in', :class => 'btn btn-lg btn-success btn-block', data: { disable_with: "<i class='fa fa-spinner fa-spin'></i> Signing In...!"} %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_order_details.html.erb
<table class="table table-striped">
	<tbody>
		<% equiptment_params.map do |key, value| %>	
			<% unless value.blank? %>
				<tr>
					<th><%= key.humanize %></th>

					<td><%= value == "true" ? "Yes" : key == "equiptment_cost" || key == "total_cost" ? number_to_currency(value.to_f) : value %></td>
				</tr>	
			<% end %>
		<% end %>
	</tbody>
</table>

app/views/shared/_plan_details.html.erb
<div class="modal fade" id="plan_details_<%= package.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Plan Details</h4>
      </div>
      <div class="modal-body">
        <div class="panel panel-default">
        	<div class="panel-body">
            <%= package.plan_details.blank? ? "N/A" : package.plan_details.html_safe %>
        	</div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-un" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_promotions.html.erb
<div class="modal fade" id="promotions_<%= package.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">More Info &amp; Promotions</h4>
      </div>
      <div class="modal-body">
        <div class="panel panel-default">
        	<div class="panel-body">
        		<%= package.promotions.blank? ? "N/A" : package.promotions.html_safe %>
        	</div>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-un" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/shared/_search_deals.html.erb
<%= form_tag offers_path, method: :get, id: "search-deals-offer-form", class: "form-inline" do %>
  <div class="panel panel-search home_form pop-msg" data-toggle="popover" data-trigger="manual" title="<span class='search-form-popover-title'>Find your offer</span>" data-content="Please enter your zipcode and find available deals and offers." data-html="true" tabindex="0">
    <div class="panel-body">
      <h4 class="search-title">
        Compare and Choose Your TV, Internet and Phone Services
      </h4>
      <p>ENTER YOUR ADDRESS</p>
      <ul class="list-inline">
        <%= hidden_field_tag :filters, "tv_filter" %>
        <li class="col-md-4 col-sm-4 col-xs-12">
          <div class="form-group">
            <%= text_field_tag :address, params[:address], class: "col-md-3 form-control address-bar", placeholder: "Street Address*" %>
          </div>
        </li>
        <li class="col-md-2 col-xs-12 col-sm-2">
          <div class="form-group">
            <%= text_field_tag :apt, params[:apt], class: "col-md-3 form-control apt-bar", placeholder: "Apt#" %>
          </div>
        </li>
        <li class="col-md-3 col-xs-12 col-sm-3">
          <div class="form-group">
            <%= text_field_tag :zipcode, params[:zipcode], class: "col-md-3 form-control zipcode-bar", placeholder: "Zip Code*" %>
          </div>
        </li>
        <li class="col-md-3 col-xs-12 col-sm-3">
          <div class="form-group">
            <%= text_field_tag :state, params[:state], class: "col-md-3 form-control state-bar", placeholder: "State*" %>
          </div>
        </li>
      </ul>
      <br />
      <%= button_tag "Find Deals &amp; Offers".html_safe, type: :submit, class: "btn btn-block btn-danger search-btn" %>
    </div>
  </div>
<% end %>

app/views/shared/_searched_filters.html.erb
<%= form_tag offers_path, method: :get do %>
	<div class="providers">
		<div class="section-3">
	    <div class="container">
	      <div class="packages-category-name">
					<div class="filters_heading">
	          Filters
	        </div>
	        <ul class="list-inline">
	          <li>
	            <a href="javascript:void(0);" class="filtering" aria-controls="tv" role="tab" onclick="applyFilters(this);" data-value="Cable">
	              TV

	            	<% if params["filters"] and params["filters"].include?("tv_filter") %>
	            		<%= check_box_tag "filters", "tv_filter", true, class: "hidden" %>
	              	<span class="package-filter" style="background-image: url(<%= asset_path('filter-circle-select.png') %>);"></span>
	            	<% else %>
	            		<%= check_box_tag "filters", "tv_filter", false, class: "hidden" %>
	            		<span class="package-filter"></span>
	            	<% end %>
	            </a>
	          </li>
	          <li>
	            <a href="javascript:void(0);" class="filtering" aria-controls="internet" role="tab" onclick="applyFilters(this);" data-value="Internet">
	              INTERNET

	              <% if params["filters"] and params["filters"].include?("internet_filter") %>
	              	<%= check_box_tag "filters", "internet_filter", true, class: "hidden" %>
	              	<span class="package-filter" style="background-image: url(<%= asset_path('filter-circle-select.png') %>);"></span>
	            	<% else %>
	            		<%= check_box_tag "filters", "internet_filter", false, class: "hidden" %>
	            		<span class="package-filter"></span>
	            	<% end %>

	            </a>
	          </li>
	          <li>
	            <a href="javascript:void(0);" class="filtering" aria-controls="phone" role="tab" onclick="applyFilters(this);" data-value="Phone">
	              PHONE

	              <% if params["filters"] and params["filters"].include?("phone_filter") %>
	              	<%= check_box_tag "filters", "phone_filter", true, class: "hidden" %>
	              	<span class="package-filter" style="background-image: url(<%= asset_path('filter-circle-select.png') %>);"></span>
	            	<% else %>
	            		<%= check_box_tag "filters", "phone_filter", false, class: "hidden" %>
	            		<span class="package-filter"></span>
	            	<% end %>
	            </a>
	          </li>
						<li>
	            <a href="javascript:void(0);" class="filtering" aria-controls="bundles" role="tab" onclick="applyFilters(this);" data-value="Bundles">
	              BUNDLES

	              <% if params["filters"] and params["filters"].include?("bundle_filter") %>
	              	<%= check_box_tag "filters", "bundle_filter", true, class: "hidden" %>
	              	<span class="package-filter" style="background-image: url(<%= asset_path('filter-circle-select.png') %>);"></span>
	            	<% else %>
	            		<%= check_box_tag "filters", "bundle_filter", false, class: "hidden" %>
	            		<span class="package-filter"></span>
	            	<% end %>
	            </a>
	          </li>
	        </ul>
	      </div>
	    </div>
	  </div>
	</div>
<% end %>

<script type="text/javascript">
	$(function() {
		window.applyFilters = (function(elem) {
			$elem = $(elem);
			$form = $elem.closest("form");
			$field = $elem.find("input[type='checkbox']");

			$.each($form.find("input[type='checkbox']"), function() {
				if($(this).attr("checked")) {
					$(this).removeAttr("checked");
				}
			});

			$field.prop("checked", "checked");


			return $form.submit();
		});
	});
</script>

app/views/shared/_slider.html.erb
<div id="search-deals">
  <div class="mobile-view">
    <%= render partial: "shared/search_deals" %>
  </div>
  <div class="desktop-view">
    <%= render partial: "shared/search_deals" %>
    <div id="myCarousel" class="carousel slide">
      <div class="carousel-inner">
        <div class="item active">
          <!--<img src="img/slider/Fotolia_30977559_XS.jpg" alt="slide 1">-->
          <%= image_tag("twc-banner.png", class: "slider-img") %>
          <div class="container">
            <div class="carousel-caption">
              <!-- Caption -->
            </div>
          </div>
          <!-- Hot Offers TWC Start -->
          <div class="landing">
            <div class="section-1">
              <div class="row">
                <div class="col-lg-12">
                  <h1 class="page-header text-center">
                    HOT OFFERS
                  </h1>
                </div>
                <%= render partial: "shared/hot_offers/twc" %>
              </div>
            </div>
          </div>
          <!-- Hot Offers TWC End -->
        </div>
        <div class="item">
          <%= image_tag("cox-banner.png", class: "slider-img") %>
          <div class="container">
            <div class="carousel-caption">
              <!-- Caption -->
            </div>
          </div>
          <!-- Hot Offers COX Start -->
          <div class="landing">
            <div class="section-1">
              <div class="row">
                <div class="col-lg-12">
                  <h1 class="page-header text-center">
                    HOT OFFERS
                  </h1>
                </div>
                <%= render partial: "shared/hot_offers/cox" %>
              </div>
            </div>
          </div>
          <!-- Hot Offers COX End -->
        </div>
        <div class="item">
          <%= image_tag("charter-banner.png", class: "slider-img") %>
          <div class="container">
            <div class="carousel-caption">
             <!-- Caption -->
            </div>
          </div>
          <!-- Hot Offers CHARTER Start -->
          <div class="landing">
            <div class="section-1">
              <div class="row">
                <div class="col-lg-12">
                  <h1 class="page-header text-center">
                    HOT OFFERS
                  </h1>
                </div>
                <%= render partial: "shared/hot_offers/charter" %>
              </div>
            </div>
          </div>
          <!-- Hot Offers CHARTER End -->
        </div>
      </div>
      <!-- Controls -->
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="fa fa-chevron-left fa-2x"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="fa fa-chevron-right fa-2x"></span></a>
    </div>
  </div>
  <!-- /.carousel -->
</div>