config/routes.rb
Rails.application.routes.draw do
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#show', via: :get, :as => :admin_checkout
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#update', via: :put

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  resources :orders

  get 'ping' => proc {|env| [200, {}, []] }

  resources :offers, only: :index do
    resources :checkout, controller: 'offers/checkout'do
      post "/" => "offers/checkout#show"
    end
  	collection do
  		get "show" => "offers#show"
      get "broadband_providers" => "offers#broadband_providers", :constraints => {:format => /(json)/}
  	end
  end

  %w(cox charter_spectrum twc dashboard).each do |proivder|
    get proivder => "landings##{proivder}"
  end

  get "/compare_packages" => "landings#compare_packages"
  get "/load_channels" => "landings#load_channels"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  devise_for :users, :skip => [:registrations], controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'registration'
    delete 'users/:id' => 'devise/registrations#destroy', :as => 'destroy_user_registration'
  end

  resources :call_back, only: [:create]
  root to: 'landings#index'
end

app/controllers/offers/checkout_controller.rb
class Offers::CheckoutController < ApplicationController
	include Wicked::Wizard
	include ApplicationHelper

	before_action :set_package, only: [:show, :installation_fields, :update]
	before_action :set_installation, only: [:show]
	before_action :exclude_params, only: [:show, :update]

	steps(*Package.checkout_steps)

	def show
		logger.debug "Step: #{step}"
		case step.to_s
		when "extra_equiptments"
			begin
				@package_bundles = @package.package_bundles
				@products = Product.where("id in (?)", @package_bundles.map(&:product_id))
			rescue Exception
				redirect_to root_path, flash: { warning: "There was a problem, Please contact Tech Support Team!" }
			end
		when "reserve_order"
			@order = Order.new
			saved_equiptments
			current_user || @order.build_user
		end
		render_wizard
	end

	def update
		logger.debug "Update Step: #{step}"
		case step.to_s
		when "extra_equiptments"
			session[:checkout_form_params] = @equiptment_params
			render_wizard @package
		end
	end

	private

	def set_package
		begin
			@package = Package.find(params[:offer_id])
			@provider = @package.provider
		rescue ActiveRecord::RecordNotFound
			flash[:error] = "Package not found"
  		redirect_to offers_path
		end
	end

	def exclude_params
  	@equiptment_params = params.except(:authenticity_token, :utf8, :_method, :action, :controller, :offer_id, :id)
	end

	def saved_equiptments
		@equiptments = session[:checkout_form_params]
	end

	def set_installation
		@installation = @package.installation
	end
end

app/views/admin/checkout/_charter_checkout_fields.html.erb
<% if product.name.downcase == :cable.to_s %>
	<%= fields_for :cable do |ff| %>
		<li class="string input optional stringish" id="package_name_input">
			<% Package::CABLE_TV.each_with_index do |cable_tv, count| %>
				<h3><%= cable_tv %></h3>
				<% count += 1 %>
				<ol>
					<li>
						<label for="provider_name" class="label">
							DVR Box &amp; Service
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "dvr_box_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
					<li>
						<label for="provider_name" class="label">
							HD BOX
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "additional_hd_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>

					<li>
						<label for="provider_name" class="label">
							SD BOX
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "sd_box_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			<% end %>
		</li>
		<li>
			<label class="label">
				Premiums
			</label>
			<%= ff.select :premiums_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/charter/items_for_premiums", locals: { ff: ff } %>
		<li>
			<label class="label">
				Digital Tier 1
			</label>
			<%= ff.select :digital_tier_1_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<!-- 50 additional channel -->
		<%= ff.fields_for :digital_tier_1 do |f| %>
			<li style="display:none;">
				<legend><span>Set item for Digital Tier 1</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							50 Additional Channels
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "50_additional_channels", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				Digital Tier 2
			</label>
			<%= ff.select :digital_tier_2_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<!-- 25 additional channel -->
		<%= ff.fields_for :digital_tier_2 do |f| %>
			<li style="display:none;">
				<legend><span>Set item for Digital Tier 2</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							25 Additional Channels
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "25_additional_channels", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				International Channels
			</label>
			<%= ff.select :international_channels_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/charter/items_for_international_channels", locals: { ff: ff } %>
	<% end %>
<% elsif product.name.downcase == :internet.to_s %>
	<%= fields_for :internet do |ff| %>
		<li>
			<label class="label">
				Internet Modem
			</label>
			<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

			<%= ff.text_field "modem", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
		</li>
		<li>
			<label class="label">
				Wifi Service &amp; Equiptment
			</label>
			<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

			<%= ff.text_field "wifi", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
		</li>
	<% end %>
<% else %>
	<%= fields_for :phone do |ff| %>
		<li>
			<label class="label">
				New phone number
			</label>
			<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

			<%= ff.text_field "new_phone_number", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
		</li>
		<li>
			<label class="label">
				Old phone number
			</label>
			<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

			<%= ff.text_field "old_phone_number", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
		</li>
		<li>
			<label class="label">
				Get 200 Minutes
			</label>
			<%= ff.select :get_200_minutes, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"} %>
		</li>
		<li>
			<label class="label">
				Mexico 500
			</label>
			<%= ff.select :mexico_500, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"} %>
		</li>
		<li>
			<label class="label">
				Get 500 Minutes
			</label>
			<%= ff.select :get_500_minutes, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"} %>
		</li>
	<% end %>
<% end %>

app/views/admin/checkout/_cox_checkout_fields.html.erb
<% if product.name.downcase == :cable.to_s %>
	<%= fields_for :cable do |ff| %>
		<li class="string input optional stringish" id="package_name_input">
			<% Package::CABLE_TV.each_with_index do |cable_tv, count| %>
				<h3 style="font-weight:bold;"><%= cable_tv %></h3>
				<% count += 1 %>
				<ol>
					<!-- <li>
						<label for="is_required" class="label">
							Is Required
						</label>
						<%#= ff.select "is_required_#{count}", options_for_select(["Required", "Optional", "Not Include"]) %>
					</li> -->
					<li>
						<label for="provider_name" class="label">
							Contour Record 6 HD-DVR Receiver &amp; Service
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "contour_record_dvr_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
					<li>
						<label for="provider_name" class="label">
							Contour HD-DVR Receiver
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "contour_hd_dvr_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>

					</li>
					<li>
						<label for="provider_name" class="label">
							Contour HD Receiver
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "contour_hd_receiver_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
					<li>
						<label for="provider_name" class="label">
							Mini Box
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "mini_box_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
					<li>
						<label for="provider_name" class="label">
							Cable CARD
						</label>
						<%= ff.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= ff.text_field "cable_card_#{count}", style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			<% end %>
		</li>
		<li>
			<label class="label">
				Premium Movie Channels
			</label>
			<%= ff.select :premiums_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/cox/items_for_premiums", locals: { ff: ff } %>
		<li>
			<label class="label">
				TV Paks
			</label>
			<%= ff.select :tv_paks_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/cox/items_for_tv_paks", locals: { ff: ff } %>
	<% end %>
<% elsif product.name.downcase == :internet.to_s %>
	<%= fields_for :internet do |ff| %>
		<li>
			<label class="label">
				Internet Equiptment
			</label>
			<%= ff.select :internet_equiptment_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/cox/items_for_internet_equiptment", locals: { ff: ff } %>

		<li>
			<label class="label">
				Cox Tech Solutions
			</label>
			<%= ff.select :cox_tech_solutions_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<%= render partial: "admin/packages/shared/cox/items_for_cox_tech_solutions", locals: { ff: ff } %>

	<% end %>
<% else %>
	<%= fields_for :phone do |ff| %>
		<li>
			<label class="label">
				Long Distance
			</label>
			<%= ff.select :long_distance_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<!-- Long distance item -->
		<%= render partial: "admin/packages/shared/cox/items_for_long_distance", locals: { ff: ff } %>

		<li>
			<label class="label">
				Additional Calling Features
			</label>
			<%= ff.select :calling_features_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<%= ff.fields_for :calling_features do |f| %>
			<!-- Voice mail -->
			<li style="display:none;">
				<legend><span>Set item for Calling feature</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							Voice Mail
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "voice_mail", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				International Calling Plan
			</label>
			<%= ff.select :international_calling_plan_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<%= ff.fields_for :international_calling_plan do |f| %>
			<!-- Simply Worldwide -->
			<li style="display:none;">
				<legend><span>Set item for International Calling feature</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							Simply Worldwide
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "simply_worldwide", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				Mexico Calling Plan
			</label>
			<%= ff.select :mexico_calling_plan_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<%= ff.fields_for :mexico_calling_plan do |f| %>
			<!-- Mexico 200 plan -->
			<li style="display:none;">
				<legend><span>Set item for Mexico Calling Plan</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							Mexico 200
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "mexico_200", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				Directory Listing
			</label>
			<%= ff.select :directory_listing_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>
		<!-- Directory Listing -->
		<%= render partial: "admin/packages/shared/cox/items_for_directory_listing", locals: { ff: ff } %>

		<li>
			<label class="label">
				Telephone Equipment (EMTA)
			</label>
			<%= ff.select :telephone_equiptment_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<!-- Telephone EMTA -->
		<%= ff.fields_for :telephone_equiptment do |f| %>
			<li style="display:none;">
				<legend><span>Set item for Telephone EMTA</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							Telephone EMTA
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "telephone_emta", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				Telephone Number porting
			</label>
			<%= ff.select :telephone_no_porting_items, options_for_select(["Required", "Not Include"]), {prompt: "--Select--"}, onChange: "$packages.setRequiredFields(this);" %>
		</li>

		<%= ff.fields_for :telephone_no_porting do |f| %>
			<!-- Provider phone number service -->
			<li style="display:none;">
				<legend><span>Set item for New phone number service</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							New phone number service
						</label>
						<%= f.select "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), {prompt: "--Select--"}, class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= f.text_field "new_phone_number", style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</li>
		<% end %>

		<li>
			<label class="label">
				Directory Name
			</label>
			<%= ff.select :directory_name, options_for_select(["Required", "Not Include"]) %>
		</li>
	<% end %>
<% end %>

app/views/admin/checkout/equiptment_items.html.erb
<h3>
	<strong>Note:</strong>
	<ol>
		<li>Selecting <strong>Include</strong> will include the item in this package</li>
		<li>Selecting <strong>Add Price</strong> will allow you to add the price for the item</li>
		<li>Selecting <strong>Not Include</strong> will remove the item from package</li>
		<li>If item is not selected then it will not be included in the package neither on edit page.</li>
	</ol>
</h3>
<%= form_tag wizard_path, method: :put do %>
	<% for product in @products do %>
		<fieldset class="inputs">
			<legend><span><%= product.name %></span></legend>
			<ol>
				<%= render partial: "#{@provider.acronym}_checkout_fields", locals: { product: product } %>
			</ol>
		</fieldset>
	<% end %>
	<!-- Cox Provider other details -->


	<% if @provider.name == Provider::COX %>
	<fieldset class="inputs">
		<legend><span>Other Details</span></legend>
		<ol>
			<% if @selected_products.include?("Phone") %>
				<li>
					<label for="provider_name" class="label">
						Telephone Outlet Installation Additional
					</label>
					<%= select_tag "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), prompt: "--Select--", class: "package_select_field", onchange: "$packages.addPriceField(this);" %>
					<%= text_field_tag :outlet_install, params[:outlet_install], style: "display: none;width: calc(78% - 22px);margin-left:20%;", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
				</li>
			<% end %>
			<li>
				<label class="label">
					Cox Service Protection Plan
				</label>
				<%= select_tag "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), prompt: "--Select--", class: "package_select_field", onchange: "$packages.addPriceField(this);" %>
				<%= text_field_tag :protection_plan_service, params[:protection_plan_service], style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
			</li>
			<li>
				<label class="label">
					Service Agreement <br /> (Lock Rates Agreement)
				</label>
				<%= select_tag "checkout_select", options_for_select(["Not Include", "Add Price"]), prompt: "--Select--", class: "package_select_field", onchange: "$packages.addPriceField(this);" %>
				<%= text_field_tag :lock_rates_agreement, params[:lock_rates_agreement], style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
			</li>
		</ol>
	</fieldset>
	<% elsif @provider.name == Provider::CHARTER_SPECTRUM %>
		<% if @selected_products.include?("Internet") %>
			<fieldset class="inputs">
				<legend><span>Other Details</span></legend>
				<ol>
					<li>
						<label class="label">
							Wifi Installation
						</label>
						<%= select_tag "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), prompt: "--Select--", class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= text_field_tag :wifi_install, params[:wifi_install], style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);$packages.generateInstallationVal(thi);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</fieldset>
		<% end %>
	<% else %>
		<% if @selected_products.include?("Cable") %>
			<fieldset class="inputs">
				<legend><span>Other Details</span></legend>
				<ol>
					<li>
						<label for="provider_name" class="label">
							4th TV Install
						</label>
						<%= select_tag "checkout_select", options_for_select(["Include", "Not Include", "Add Price"]), prompt: "--Select--", class: "package_select_field", onchange: "$packages.addPriceField(this);" %>

						<%= text_field_tag :fourth_tv_install, params[:fourth_tv_install], style: "display: none;width: calc(78% - 22px);", onblur: "$packages.packagePriceValidation(this);", class: "admin_checkout_price" %>
					</li>
				</ol>
			</fieldset>
		<% end %>
	<% end %>


	<%= button_tag "Create Package", type: :submit %>
	<%= link_to "Cancel", admin_packages_path %>
<% end %>

app/views/admin/checkout/package_bundles.html.erb
<%= form_tag wizard_path, method: "put" do %>
	<% for product in @products do %>
    <% input_value = "" %>
    <% package_bundle_fields = get_in_hash(@package.package_bundles.find_by_product_id(product).field) %>
		<% if @provider_preferences.preferences_of_product(product.id).present? %>
			<fieldset class="inputs">
				<legend><span><%= product.name %></span></legend>
				<ol>
					<% @provider_preferences.preferences_of_product(product.id).each do |preference| %>
          
            <% if package_bundle_fields.present? and package_bundle_fields[preference.additional_field_weight.to_field.to_s].present? %>
              <% input_value = package_bundle_fields[preference.additional_field_weight.to_field.to_s] %>
            <% end %>

						<li class="string input optional stringish" id="package_name_input">
							<label for="provider_name" class="label">
								<%= preference.additional_field_weight.additional_weight %>
							</label>
							<% if preference.additional_field_weight.field_type == "Select Multiple" %>

								<%= select_tag "#{preference.additional_field_weight.to_field}[]", options_for_select(preference.additional_field_weight.get_values.map{|m| m}, input_value), prompt: "--Select #{preference.additional_field_weight.additional_weight.pluralize}--", multiple: true %>

							<% elsif preference.additional_field_weight.field_type == "Select" %>

								<%= select_tag preference.additional_field_weight.to_field, options_for_select(preference.additional_field_weight.get_values.map{|m| m}), prompt: "--Select #{preference.additional_field_weight.additional_weight.humanize}--", value: input_value %>

							<% else %>
								<%= text_field_tag preference.additional_field_weight.to_field, preference.additional_field_weight.to_field, value: input_value %>
							<% end %>
						</li>
					<% end %>
				</ol>
			</fieldset>
		<% end %>
	<% end %>
	<%= button_tag "Next", type: :submit %>
	<%= link_to "Cancel", admin_packages_path %>
<% end %>