config/routes.rb
Rails.application.routes.draw do
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#show', via: :get, :as => :admin_checkout
  match '/admin/checkout/:id/packages/:package_id' => 'admin/checkout#update', via: :put

  get "sitemap.xml" => "sitemaps#index", :format => "xml", :as => :sitemap
  resources :orders

  get 'ping' => proc {|env| [200, {}, []] }

  resources :offers, only: :index do
    resources :checkout, controller: 'offers/checkout'do
      post "/" => "offers/checkout#show"
    end
  	collection do
  		get "show" => "offers#show"
      get "broadband_providers" => "offers#broadband_providers", :constraints => {:format => /(json)/}
  	end
  end

  %w(cox charter_spectrum twc dashboard).each do |proivder|
    get proivder => "landings##{proivder}"
  end

  get "/compare_packages" => "landings#compare_packages"
  get "/load_channels" => "landings#load_channels"

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  # devise_for :users, controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  devise_for :users, :skip => [:registrations], controllers: { sessions: "users/sessions", :registrations => "users/registrations" }
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users/:id' => 'devise/registrations#update', :as => 'registration'
    delete 'users/:id' => 'devise/registrations#destroy', :as => 'destroy_user_registration'
  end

  resources :call_back, only: [:create]
  root to: 'landings#index'
end

app/controllers/offers/checkout_controller.rb
class Offers::CheckoutController < ApplicationController
	include Wicked::Wizard
	include ApplicationHelper

	before_action :set_package, only: [:show, :installation_fields, :update]
	before_action :set_installation, only: [:show]
	before_action :exclude_params, only: [:show, :update]

	steps(*Package.checkout_steps)

	def show
		logger.debug "Step: #{step}"
		case step.to_s
		when "extra_equiptments"
			begin
				@package_bundles = @package.package_bundles
				@products = Product.where("id in (?)", @package_bundles.map(&:product_id))
			rescue Exception
				redirect_to root_path, flash: { warning: "There was a problem, Please contact Tech Support Team!" }
			end
		when "reserve_order"
			@order = Order.new
			saved_equiptments
			current_user || @order.build_user
		end
		render_wizard
	end

	def update
		logger.debug "Update Step: #{step}"
		case step.to_s
		when "extra_equiptments"
			session[:checkout_form_params] = @equiptment_params
			render_wizard @package
		end
	end

	private

	def set_package
		begin
			@package = Package.find(params[:offer_id])
			@provider = @package.provider
		rescue ActiveRecord::RecordNotFound
			flash[:error] = "Package not found"
  		redirect_to offers_path
		end
	end

	def exclude_params
  	@equiptment_params = params.except(:authenticity_token, :utf8, :_method, :action, :controller, :offer_id, :id)
	end

	def saved_equiptments
		@equiptments = session[:checkout_form_params]
	end

	def set_installation
		@installation = @package.installation
	end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	@@broadband_providers = []
	include PackagesHelper

	def show
		@packages = []

		address_params = {
			address: params[:address],
			zip: params[:zipcode],
			apt: params[:apt],
			state: params[:state]
		}

		unless address_params[:address].blank?
			session[:zip_code] = address_params[:zip]

			user_address = Address.new(address_params).get_address
			session[:user_address] = user_address
		end

		unless broadband_search.to_s == "zero_results"
			@providers = broadband_search
			@packages = Package.broadband_providers(@providers)
		end

		if @packages.length > 0
			# Applying product filters
			if params[:filters] and params[:filters].present?
				@packages = @packages.send(params[:filters])
			end

			@count_twc = @packages.try("time_warner").length
			@count_charter = @packages.try("charter_spectrum").length
			@count_cox = @packages.try("cox").length

			@packages = @packages.paginate(:page => params[:page], :per_page => 6)
		end

		respond_to do |format|
			format.html
		end
	end

	def broadband_providers
		@location = params

		@address = Address.new
		@results = @address.search_providers(@location)

		logger.debug @results

		if @results == "error".to_sym
			render json: { status: :error, msg: "There was a problem while fetching data." }
		else
			session[:broadband_search] = @results
			render json: { status: :ok }
		end
	end
end

app/views/offers/show.html.erb
<div id="results-banner">
	<div class="row">
		<div class="col-md-6 address">
			<strong>Offer Showing for:</strong>
			<address><%= user_address %></address>
			<i class="glyphicon glyphicon-edit"></i> <%= link_to "Change Address", root_path, class: "change-address-link" %>
		</div>
		<div class="col-md-6 companies">
			<strong>Our Providers</strong>
				<ul class="list-inline">
					<li class="text-center">
						<%= image_tag("twc-search.png") %>
						(<%= @count_twc || 0 %>)
					</li>
					<li class="text-center">
						<%= image_tag("cox-search.png") %>
						(<%= @count_cox || 0 %>)
					</li>
					<li class="text-center">
						<%= image_tag("charter-search.png") %>
						(<%= @count_charter || 0 %>)
					</li>
				</ul>
		</div>
	</div>
</div>
<div id="package-details">
	<!-- Search filters -->
	<%= render partial: "shared/searched_filters" %>

	<div class="container">
		<% if @packages.blank? %>
			<div class="alert alert-danger">
				<strong>Sorry!</strong> There are no packages available.
			</div>
		<% else %>
			<div class="row">
				<% @packages.each do |package| %>
					<div class="col-md-6 col-sm-12">
						<div class="panel panel-default packages">
							<div class="panel-body">
								<div class="row">
									<div class="col-md-9 col-sm-9">
										<div class="offers-package-heading">
											<div class="row">
												<div class="col-md-4 col-sm-4">
													<%= provider_logo(package.provider) %>
												</div>
												<div class="form-group"></div>
												<div class="col-md-8 col-sm-8">
													<label><%= package.package_name %></label>
													<br />
													<%= link_to "Plan Details", "#", class: "detail-link", "data-toggle" => "modal", "data-target" => "#plan_details_#{package.id}" %>
													<%= render partial: "shared/plan_details", locals: { package: package } %>
												</div>
											</div>
										</div>


										<div class="offers-package-desc">
											<%= package.package_description.blank? ? "N/A" : package.package_description.html_safe %>
										</div>

										<%= link_to "More Info & Promotions", "#", class: "detail-link", class: "detail-link", "data-toggle" => "modal", "data-target" => "#promotions_#{package.id}" %>
										<%= render partial: "shared/promotions", locals: { package: package } %>
										<% if package.package_bundles.map(&:product).map(&:name).include?("Cable") %>
											<br />
											<a href="#" class="channel-comparison-link" data-provider="<%= channel_provider_names(package.provider.try("name")) %>">Channel List</a>
										<% end %>
										<br /><br />
										<%= link_to "CHOOSE THIS PLAN", offer_checkout_path(package, Package.checkout_steps.first.to_s), class: "btn btn-warning btn-lg choose-plan-btn" %>
									</div>
									<div class="col-md-3 col-sm-3">
										<div class="price-info">
											<strong>Starting at</strong>
											<strong class="price"><%= package.price.present? ? number_to_currency(package.price) : package.price %></strong>
											per month
											<br />
											<strong class="price-information"><%= package.price_info %></strong>
										</div>
										<div class="checkbox">
			                <%= check_box_tag :compare, false, false, {:class => "styled compare_box", onchange: "compareMe(this);", data: { package_id: package.id, :compare_url => compare_packages_path }}  %>
			                <label class="label-checkbox">
			                  COMPARE
			                </label>
			              </div>
									</div>
								</div>
							</div>
						</div>
					</div>
				<% end %>
			</div>
			<ul class="list-inline pull-right">
				<li>
					<%= will_paginate @packages, renderer: BootstrapPagination::Rails, class: "pull-right" %>
				</li>
				<li>
					<%= button_tag class: "btn btn-info pull-right", id: "compare_packages", style: "margin: 20px 0;" do %>
						<i class="glyphicon glyphicon-random"></i> Compare Packages
					<% end %>
				</li>
			</ul>
		<% end %>
	</div>

</div>

<div id="comparison"></div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>